package cn.kjy.zj.pojo;

// Generated 2017-3-14 17:39:57 by Hibernate Tools 3.4.0.CR1

/**
 * HatArea generated by hbm2java
 */
public class HatArea implements java.io.Serializable {

	private Integer id;
	private HatCity hatCity;
	private String areaId;
	private String area;

	public HatArea() {
	}

	public HatArea(HatCity hatCity, String areaId, String area) {
		this.hatCity = hatCity;
		this.areaId = areaId;
		this.area = area;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public HatCity getHatCity() {
		return this.hatCity;
	}

	public void setHatCity(HatCity hatCity) {
		this.hatCity = hatCity;
	}

	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

}
