package cn.kjy.zj.pojo;

// Generated 2017-3-14 17:39:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * HatProvince generated by hbm2java
 */
public class HatProvince implements java.io.Serializable {

	private String provinceId;
	private Integer id;
	private String province;
	private Set<HatCity> hatCities = new HashSet<HatCity>(0);

	public HatProvince() {
	}

	public HatProvince(String provinceId, Integer id) {
		this.provinceId = provinceId;
		this.id = id;
	}

	public HatProvince(String provinceId, Integer id, String province, Set<HatCity> hatCities) {
		this.provinceId = provinceId;
		this.id = id;
		this.province = province;
		this.hatCities = hatCities;
	}

	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public Set<HatCity> getHatCities() {
		return this.hatCities;
	}

	public void setHatCities(Set<HatCity> hatCities) {
		this.hatCities = hatCities;
	}

}
